---
title: "descriptive Statistics"
author: "Aepril Jean A. Binwag"
date: "2023-01-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## JUST EXPLORING DESCRIPTIVE STATISTICS

```{r}
# If .txt tab file, use this
my_data <- read.delim(file.choose())
# Or, if .csv file, use this
my_data <- read.csv(file.choose())
```

```{r}
# Store the data in the variable my_data
my_data <- iris
```

```{r}
# Print the first 6 rows
head(my_data, 6)
```
```{r}
# Compute the mean value
mean(my_data$Sepal.Length)
```
```{r}
# Compute the median value
median(my_data$Sepal.Length)
```
```{r}
# Compute the mode
# install.packages("modeest")
require(modeest)
mfv(my_data$Sepal.Length)
```
```{r}
# Compute the minimum value
min(my_data$Sepal.Length)
```
```{r}
# Compute the maximum value
max(my_data$Sepal.Length)
```
```{r}
# Range
range(my_data$Sepal.Length)

```

```{r}
quantile(my_data$Sepal.Length)
```
```{r}
quantile(my_data$Sepal.Length, seq(0, 1, 0.1))
```
```{r}
IQR(my_data$Sepal.Length)
```
```{r}
# Compute the variance
var(my_data$Sepal.Length)
# Compute the standard deviation =
# square root of th variance
sd(my_data$Sepal.Length)
```
```{r}
# Compute the median
median(my_data$Sepal.Length)
# Compute the median absolute deviation
mad(my_data$Sepal.Length)
```
```{r}
summary(my_data$Sepal.Length)
```
```{r}
summary(my_data, digits = 1)
```
```{r}
# Compute the mean of each column
sapply(my_data[, -5], mean)
```
```{r}
# Compute quartiles
sapply(my_data[, -5], quantile)
```
```{r}
# Compute descriptive statistics
library(pastecs)
res <- stat.desc(my_data[, -5])
round(res, 2)
```
```{r}
mean(my_data$Sepal.Length, na.rm = TRUE)
```
```{r}
library(ggpubr)
```
```{r}
ggboxplot(my_data, y = "Sepal.Length", width = 0.5)
```
```{r}
gghistogram(my_data, x = "Sepal.Length", bins = 9, 
             add = "mean")
```
```{r}
ggecdf(my_data, x = "Sepal.Length")
```
```{r}
ggqqplot(my_data, x = "Sepal.Length")
```

```{r}
library(dplyr)
group_by(my_data, Species) %>% 
summarise(
  count = n(), 
  mean = mean(Sepal.Length, na.rm = TRUE),
  sd = sd(Sepal.Length, na.rm = TRUE)
  )
```
```{r}
library("ggpubr")
# Box plot colored by groups: Species
ggboxplot(my_data, x = "Species", y = "Sepal.Length",
          color = "Species",
          palette = c("#00AFBB", "#E7B800", "#FC4E07"))
```
```{r}
# Stripchart colored by groups: Species
ggstripchart(my_data, x = "Species", y = "Sepal.Length",
          color = "Species",
          palette = c("#00AFBB", "#E7B800", "#FC4E07"),
          add = "mean_sd")
```
```{r}
# Hair/eye color data
df <- as.data.frame(HairEyeColor)
hair_eye_col <- df[rep(row.names(df), df$Freq), 1:3]
rownames(hair_eye_col) <- 1:nrow(hair_eye_col)
head(hair_eye_col)
```
```{r}
# hair/eye variables
Hair <- hair_eye_col$Hair
Eye <- hair_eye_col$Eye
```

```{r}
# Frequency distribution of hair color
table(Hair)
```
```{r}
# Frequency distribution of eye color
table(Eye)
```
```{r}
# Compute table and convert as data frame
df <- as.data.frame(table(Hair))
df
```
```{r}
# Visualize using bar plot
library(ggpubr)
ggbarplot(df, x = "Hair", y = "Freq")
```
```{r}
tbl2 <- table(Hair , Eye)
tbl2
```
```{r}
xtabs(~ Hair + Eye, data = hair_eye_col)
```
```{r}
df <- as.data.frame(tbl2)
head(df)
```
```{r}
# Visualize using bar plot
library(ggpubr)
ggbarplot(df, x = "Hair", y = "Freq",
          color = "Eye", 
          palette = c("brown", "blue", "gold", "green"))
```
```{r}
# position dodge
ggbarplot(df, x = "Hair", y = "Freq",
          color = "Eye", position = position_dodge(),
          palette = c("brown", "blue", "gold", "green"))
```
```{r}
xtabs(~Hair + Eye + Sex, data = hair_eye_col)
```
```{r}
ftable(Sex + Hair ~ Eye, data = hair_eye_col)
```

```{r}
Hair <- hair_eye_col$Hair
Eye <- hair_eye_col$Eye
# Hair/Eye color table
he.tbl <- table(Hair, Eye)
he.tbl
```
```{r}
# Margin of rows
margin.table(he.tbl, 1)
```
```{r}
# Margin of columns
margin.table(he.tbl, 2)
```
```{r}
# Frequencies relative to row total
prop.table(he.tbl, 1)
```
```{r}
# Table of percentages
round(prop.table(he.tbl, 1), 2)*100
```
```{r}
he.tbl/sum(he.tbl)
```


